GET https://meg-backend.herokuapp.com

###


POST  https://meg-backend.herokuapp.com/login HTTP/1.1
content-type: application/json

{
    "email": "newonet@mail.com",
    "password": "newonenewone"
}

###

POST  https://meg-backend.herokuapp.com/logout HTTP/1.1

###

POST  https://meg-backend.herokuapp.com/signup HTTP/1.1
content-type: application/json

{
    "email": "jwttest@mail.com",
    "password": "jwttest123"
}

###

GET  https://meg-backend.herokuapp.com/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp3dHRlc3RAbWFpbC5jb20iLCJ1c2VySWQiOjcsImlhdCI6MTY4NjA5Nzc1OSwiZXhwIjoxNjg2MTA4NTU5fQ.ZsEX_r10xXwzy1VMNpAlcEFZywX0ESdk0TSU4PTR1io