GET http://127.0.0.1:3001/

###

POST  http://127.0.0.1:3001/login HTTP/1.1
content-type: application/json

{
    "email": "signup_email",
    "password": "signup_password"
}

###

POST  http://127.0.0.1:3001/logout HTTP/1.1

###

POST  http://127.0.0.1:3001/signup HTTP/1.1
content-type: application/json

{
    "email": "signup_email",
    "password": "signup_password"
}