POST  http://127.0.0.1:3001/api/journey HTTP/1.1
content-type: application/json

{
          "userId": 1,
          "type": "uber",
          "details": "driving service",
          "startTime": "10",
          "endTime": "10",
          "route": "asasd",
          "name": "mike jones",
          "username": "mikejones2200",
          "licensePlate": "azaxaz",
          "color": "blue",
          "year": "2000",
          "make": "Ford",
          "model": "Fusion",
          "image": null
        }
